{% set name = "llvm-spirv" %}
{% set llvm_version = "12.0.1" %}
{% set version = "12.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/v{{ version.replace("_", "-") }}.tar.gz
  sha256: 6e4fad04203f25fcde4c308c53e9f59bd05a390978992db3212d4b63aff62108

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - llvmdev  {{ llvm_version }}
    - llvm  {{ llvm_version }}
  run_constrained:
    - llvmdev  {{ llvm_version }}

test:
  commands:
    - llvm-spirv -help

about:
  home: https://github.com/KhronosGroup/SPIRV-LLVM-Translator
  license: NCSA
  license_file: LICENSE.TXT
  license_family: BSD
  summary: A tool and a library for bi-directional translation between SPIR-V and LLVM IR

extra:
  recipe-maintainers:
    - isuruf
