{% set name = "llvm-spirv" %}
{% set version = "18.1.0" %}
{% set llvm_version = ".".join(version.split(".")[:2]) %}
{% set major = version.split('.')[0] %}
# https://www.phoronix.com/news/LLVM-N-1-Stable-Versioning
{% if major | int >= 18 %}
{% set abi_version = ".".join(version.split(".")[:2]) %}
{% else %}
{% set abi_version = version.split('.')[0] %}
{% endif %}

package:
  name: llvm-spirv-split
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/v{{ version.replace("_", "-") }}.tar.gz
  sha256: 78a770eff24d5ffe2798479845adec4b909cbf058ddc55830ea00fa7d2c1698a

build:
  number: 0
  skip: true  # [not unix]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - llvmdev  {{ llvm_version }}.*
    - llvm  {{ llvm_version }}.*
    - spirv-headers
    - zlib

outputs:
  - name: libllvmspirv{{ major }}
    script: install.sh
    build:
      ignore_run_exports_from:
        - zlib
    files:
      - lib/libLLVMSPIRVLib.{{ abi_version }}.dylib  # [osx]
      - lib/libLLVMSPIRVLib.so.{{ abi_version }}     # [linux]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make
        - pkg-config
      host:
        - llvmdev  {{ llvm_version }}.*
        - llvm  {{ llvm_version }}.*
        - zlib
        - spirv-headers
      run_constrained:
        - llvmdev  {{ llvm_version }}.*
        - llvm-spirv {{ version }}.* *_{{ PKG_BUILDNUM }}
    test:
      commands:
        - test ! -f ${PREFIX}/lib/libLLVMSPIRVLib${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libLLVMSPIRVLib.{{ abi_version }}.dylib  # [osx]
        - test -f ${PREFIX}/lib/libLLVMSPIRVLib.so.{{ abi_version }}     # [linux]

  - name: libllvmspirv
    script: install.sh
    build:
      run_exports:
        - {{ pin_subpackage("libllvmspirv" ~ major) }}
      ignore_run_exports_from:
        - zlib
    files:
      - lib/libLLVMSPIRVLib.dylib       # [osx]
      - lib/libLLVMSPIRVLib.so          # [linux]
      - lib/pkgconfig/LLVMSPIRVLib.pc
      - include/LLVMSPIRVLib/
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make
        - pkg-config
      host:
        - llvmdev  {{ llvm_version }}.*
        - llvm  {{ llvm_version }}.*
        - zlib
        - spirv-headers
        - {{ pin_subpackage("libllvmspirv" ~ major, exact=True) }}
      run:
        - {{ pin_subpackage("libllvmspirv" ~ major, exact=True) }}
      run_constrained:
        - llvmdev  {{ llvm_version }}.*
    test:
      commands:
        - test -f ${PREFIX}/lib/libLLVMSPIRVLib${SHLIB_EXT}

  - name: llvm-spirv-{{ major }}
    script: install.sh
    build:
      ignore_run_exports_from:
        - zlib
    files:
      - bin/llvm-spirv-{{ major }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make
        - pkg-config
      host:
        - llvmdev  {{ llvm_version }}.*
        - llvm  {{ llvm_version }}.*
        - zlib
        - spirv-headers
        - {{ pin_subpackage("libllvmspirv" ~ major, exact=True) }}
      run:
        - {{ pin_subpackage("libllvmspirv" ~ major, exact=True) }}
    test:
      commands:
        - ${PREFIX}/bin/llvm-spirv-{{ major }} -help

  - name: llvm-spirv
    script: install.sh
    build:
      ignore_run_exports_from:
        - zlib
    files:
      - bin/llvm-spirv
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make
        - pkg-config
      host:
        - llvmdev  {{ llvm_version }}.*
        - llvm  {{ llvm_version }}.*
        - zlib
        - spirv-headers
        - {{ pin_subpackage("llvm-spirv-" ~ major, exact=True) }}
      run:
        - {{ pin_subpackage("llvm-spirv-" ~ major, exact=True) }}
    test:
      commands:
        - ${PREFIX}/bin/llvm-spirv -help
        - llvm-spirv -help

about:
  home: https://github.com/KhronosGroup/SPIRV-LLVM-Translator
  license: NCSA
  license_file: LICENSE.TXT
  license_family: BSD
  summary: A tool and a library for bi-directional translation between SPIR-V and LLVM IR

extra:
  feedstock-name: llvm-spirv
  recipe-maintainers:
    - isuruf
    - matthiasdiener
    - ZzEeKkAa
