{% set name = "llvm-spirv" %}
{% set version = "16.0.4" %}
{% set llvm_version = ".".join(version.split(".")[:2]) %}
{% set major = version.split('.')[0] %}
# https://www.phoronix.com/news/LLVM-N-1-Stable-Versioning
{% if major | int >= 18 %}
{% set abi_version = ".".join(version.split(".")[:2]) %}
{% else %}
{% set abi_version = version.split('.')[0] %}
{% endif %}
{% set library = "Library/" if win else "" %}

package:
  name: llvm-spirv-split
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/v{{ version.replace("_", "-") }}.tar.gz
  sha256: 9a42104fc677debc7e17c1d6781c4e20633b3442777acf8722bef7d9f1fe3d4c
  patches:
    # https://github.com/llvm/llvm-project/issues/83802
    - patches/0001-Work-around-a-bug-in-the-llvm-config.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
    - make   # [not win]
    - pkg-config
  host:
    - llvmdev  {{ llvm_version }}.*
    - llvm  {{ llvm_version }}.*
    - spirv-headers
    - spirv-tools  # [not win]
    - zlib

outputs:
  - name: libllvmspirv{{ major }}
    script: install.sh
    build:
      ignore_run_exports_from:
        - zlib
        - spirv-tools
      skip: true  # [win]
    files:
      - lib/libLLVMSPIRVLib.{{ abi_version }}.dylib  # [osx]
      - lib/libLLVMSPIRVLib.so.{{ abi_version }}     # [linux]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make
        - pkg-config
      host:
        - llvmdev  {{ llvm_version }}.*
        - llvm  {{ llvm_version }}.*
        - zlib
        - spirv-headers
        - spirv-tools
      run_constrained:
        - llvmdev  {{ llvm_version }}.*
        - llvm-spirv {{ version }}.* *_{{ PKG_BUILDNUM }}
    test:
      commands:
        - test ! -f ${PREFIX}/lib/libLLVMSPIRVLib${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libLLVMSPIRVLib.{{ abi_version }}.dylib  # [osx]
        - test -f ${PREFIX}/lib/libLLVMSPIRVLib.so.{{ abi_version }}     # [linux]

  - name: libllvmspirv
    script: install.sh  # [not win]
    script: install.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("libllvmspirv" ~ major) }}  # [not win]
      ignore_run_exports_from:
        - zlib
        - spirv-tools  # [not win]
      script_env:
        - MAJOR_VERSION={{ major }}  # [win]
    files:
      - lib/libLLVMSPIRVLib.dylib          # [osx]
      - lib/libLLVMSPIRVLib.so             # [linux]
      - {{ library }}lib/LLVMSPIRVLib.lib  # [win]
      - {{ library }}lib/pkgconfig/LLVMSPIRVLib.pc
      - {{ library }}include/LLVMSPIRVLib/
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make
        - pkg-config
      host:
        - llvmdev  {{ llvm_version }}.*
        - llvm  {{ llvm_version }}.*
        - zlib
        - spirv-headers
        - spirv-tools  # [not win]
        - {{ pin_subpackage("libllvmspirv" ~ major, exact=True) }}  # [not win]
      run:
        - {{ pin_subpackage("libllvmspirv" ~ major, exact=True) }}  # [not win]
      run_constrained:
        - llvmdev  {{ llvm_version }}.*
    test:
      commands:
        - test -f ${PREFIX}/lib/libLLVMSPIRVLib${SHLIB_EXT}      # [not win]
        - if not exist "%LIBRARY_LIB%"\\LLVMSPIRVLib.lib exit 1  # [win]

  - name: llvm-spirv-{{ major }}
    script: install.sh  # [not win]
    script: install.bat  # [win]
    build:
      ignore_run_exports_from:
        - zlib
      script_env:
        - MAJOR_VERSION={{ major }}  # [win]
    files:
      - bin/llvm-spirv-{{ major }}                   # [not win]
      - {{ library }}bin/llvm-spirv-{{ major }}.exe  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make
        - pkg-config
      host:
        - llvmdev  {{ llvm_version }}.*
        - llvm  {{ llvm_version }}.*
        - zlib
        - spirv-headers
        - spirv-tools  # [not win]
        - {{ pin_subpackage("libllvmspirv" ~ major, exact=True) }}  # [not win]
      run:
        - {{ pin_subpackage("libllvmspirv" ~ major, exact=True) }}  # [not win]
    test:
      commands:
        - ${PREFIX}/bin/llvm-spirv-{{ major }} -help         # [not win]
        - '%LIBRARY_BIN%\\llvm-spirv-{{ major }}.exe -help'  # [win]
        - llvm-spirv-{{ major }} -help

  - name: llvm-spirv
    script: install.sh  # [not win]
    script: install.bat  # [win]
    build:
      ignore_run_exports_from:
        - zlib
        - spirv-tools  # [not win]
      script_env:
        - MAJOR_VERSION={{ major }}  # [win]
    files:
      - bin/llvm-spirv                   # [not win]
      - {{ library }}bin/llvm-spirv.exe  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make
        - pkg-config
      host:
        - llvmdev  {{ llvm_version }}.*
        - llvm  {{ llvm_version }}.*
        - zlib
        - spirv-headers
        - spirv-tools  # [not win]
        - {{ pin_subpackage("llvm-spirv-" ~ major, exact=True) }}
      run:
        - {{ pin_subpackage("llvm-spirv-" ~ major, exact=True) }}
    test:
      commands:
        - ${PREFIX}/bin/llvm-spirv -help         # [not win]
        - '%LIBRARY_BIN%\\llvm-spirv.exe -help'  # [win]
        - llvm-spirv -help

about:
  home: https://github.com/KhronosGroup/SPIRV-LLVM-Translator
  license: NCSA
  license_file: LICENSE.TXT
  license_family: BSD
  summary: A tool and a library for bi-directional translation between SPIR-V and LLVM IR

extra:
  feedstock-name: llvm-spirv
  recipe-maintainers:
    - isuruf
    - matthiasdiener
    - ZzEeKkAa
