{% set name = "llvm-spirv" %}
{% set version = "14.0.0" %}
{% set llvm_version = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/v{{ version.replace("_", "-") }}.tar.gz
  sha256: 1afc52bb4e39aeb9b5b69324a201c81bd986364f347b559995eff6fd6f013318

build:
  number: 0
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - llvmdev  {{ llvm_version }}.*
    - llvm  {{ llvm_version }}.*
  run_constrained:
    - llvmdev  {{ llvm_version }}.*

test:
  commands:
    - llvm-spirv -help

about:
  home: https://github.com/KhronosGroup/SPIRV-LLVM-Translator
  license: NCSA
  license_file: LICENSE.TXT
  license_family: BSD
  summary: A tool and a library for bi-directional translation between SPIR-V and LLVM IR

extra:
  recipe-maintainers:
    - isuruf
